
<?php echo "\n==============================================\n";
 echo "==#### ~🇨 🇾 🇧 🇪 🇷  🇯 🇲 🇧~####==\n";
 echo "===🇦 🇺 🇹 🇴 🇨 🇱 🇦 🇮 🇲  2018-2019===\n";
 echo "=======================================\n";
 date_default_timezone_set("Asia/Jakarta");
 error_reporting(0);
 set_time_limit(0);
 ini_set("memory_limit","-1");
 ini_set("output_buffering",0);
 ini_set("request_order","GP");
 ini_set("variables_order","EGPCS");
 ini_set("max_execution_time","-1");
 $versi="Auro Claim Multicoin v.1.4.1";
 $cekVersi=file_get_contents("https://pastebin.com/raw/gNfFvZb4");
 if($versi == $cekVersi){ echo $versi;
 ${"GLOBALS"}["curl"]="curl";
 ${"GLOBALS"}["webName1"]="http://faucetnarniacoin.online/";
 ${"GLOBALS"}["webName2"]="http://faucetnarniacoin.online/";
 ${"GLOBALS"}["firstStart"]=date("Y-m-d H:i:s");
 ${"GLOBALS"}["arr"]=array();
 ${"GLOBALS"}["arr_time"]=array();
 ${"GLOBALS"}["auto_stop"]=array();
 for($y=0;
$y<1000;
$y++){ ${"GLOBALS"}["arr_time"][$y]=date("Y-m-d H:i:s");
 ${"GLOBALS"}["auto_stop"][$y]=0;
 } echo "\n====================================\n";
 echo "!!! PERINGATAN !!!\n";
 echo "Sebelum menjalankan Script ini anda harus sudah punya file config.php yang di dalamnya berisi semua key yang anda inginkan.\Jangan lupa mengganti alamat walletnya dengan wallet anda\n";
 echo "\n=====🇨 🇾 🇧 🇪 🇷  🇯 🇲 🇧=====\n";
 echo "Ketik \"lanjut nih\" (tanpa tanda petik) untuk lanjut autoclaim\n";
 $konfirm=trim(fgets(STDIN));
 if($konfirm=="lanjut nih"){ function cekURL(){ $file="config.php";
 $handle = fopen($file, "r");
 $temp="";
 if ($handle) { $arr=array();
 $ll=0;
 echo "\n=====🇨 🇾 🇧 🇪 🇷  🇯 🇲 🇧=====\nChecking URL & Key saved: \n";
 while (($line = fgets($handle)) !== false) { $temp=trim($line);
 ${"GLOBALS"}["arr"][$ll]=$temp;
 $ll++;
 echo $ll.". ".$line."\n";
 } fclose($handle);
 echo "\n====================================\n";
 if($temp != ""){ return ${"GLOBALS"}["arr"];
 } } else { echo "\n====================================\n🇨 🇾 🇧 🇪 🇷  🇯 🇲 🇧\n====================================\n🇨 🇾 🇧 🇪 🇷  🇯 🇲 🇧\n====================================\n";
 return "🇨 🇾 🇧 🇪 🇷  🇯 🇲 🇧";
 } } function checkCur($whatCur){ if (strpos($whatCur, 'POT') !== false) { return 'POT';
 }else if (strpos($whatCur, 'BTC') !== false) { return 'BTC';
 }else if (strpos($whatCur, 'BCH') !== false) { return 'BCH';
 }else if (strpos($whatCur, 'ETH') !== false) { return 'ETH';
 }else if (strpos($whatCur, 'BLK') !== false) { return 'BLK';
 }else if (strpos($whatCur, 'BTX') !== false) { return 'BTX';
 }else if (strpos($whatCur, 'DASH') !== false) { return 'DASH';
 }else if (strpos($whatCur, 'DOGE') !== false) { return 'DOGE';
 }else if (strpos($whatCur, 'LTC') !== false) { return 'LTC';
 }else if (strpos($whatCur, 'PPC') !== false) { return 'PPC';
 }else if (strpos($whatCur, 'XPM') !== false) { return 'XPM';
 } } function startClaim(){ $urlCek=cekURL();
 if($urlCek !="kosong"){ echo "\n=====🇨 🇾 🇧 🇪 🇷  🇯 🇲 🇧=====";
 echo "\nWaktu tunggu sekarang dipercepat";
 echo "\n================================";
 echo "\n==Start claiming ... ## ".${"GLOBALS"}["firstStart"]." ##\n";
 while (1){ $ll=0;
 $loopCek=1;
 foreach($urlCek as $item) { $url_exp=explode("||",trim($item));
 $whatCur=checkCur($url_exp[0]);
 $startTime = date("Y-m-d H:i:s");
 if($startTime > ${"GLOBALS"}["arr_time"][$ll]){ if($whatCur=="POT"){ $myCur="PM743ZCKdjRApgU2arHHHtxnb2NGCs1YCR";
 }else if($whatCur=="BTC"){ $myCur="1PtY1aXPaMZEEcCxB9f8uMKvpaNy5xhWJV";
 }else if($whatCur=="DOGE"){ $myCur="DDFWQcEANRYFekVaVFzgXYcsea8jgspiNi";
 }else if($whatCur=="ETH"){ $myCur="0x0ae2d8a70dfe4333a8f6bd6b22a0f42f5489b152";
 }else if($whatCur=="LTC"){ $myCur="LXGq9DWbGHfNaXW3wt2uCDRsWM55jH4wQW";
 }else if($whatCur=="BCH"){ $myCur="1MQNzZ3zY1S3ghfnd64nAwK2X15mxqGtqL";
 }else if($whatCur=="BLK"){ $myCur="BCNdUpHNCW9XX3rsUrEisWjcWPjcuZy2pj";
 }else if($whatCur=="DASH"){ $myCur="XiSMh1N4HkpUmKU4F9LQHerSTKQyLhTdfv";
 }else if($whatCur=="PPC"){ $myCur="PU2d8fVq6b8YN4QbXj6YJswBH1md1ZXbRy";
 }else if($whatCur=="XPM"){ $myCur="AdWNgKa9a6yro5kanjcaM2PS5EwLBRdP7B";
 } $claiming=claim($url_exp[0]."&r=".$myCur."&rc=".$whatCur,$whatCur);
 if($claiming !=""){ echo $whatCur." ".$claiming.",";
 } $claiming=claim($url_exp[0]."&r=".$myCur."&rc=".$whatCur,$whatCur);
 if($claiming !=""){ echo $whatCur." ".$claiming.",";
 } ${"GLOBALS"}["arr_time"][$ll] = date('Y-m-d H:i:s',strtotime('+'.((int)$url_exp[1]+10).' seconds',strtotime($startTime)));
 ${"GLOBALS"}["auto_stop"][$ll]++;
 $whatT=rand(150,300);
 if($whatT <= ${"GLOBALS"}["auto_stop"][$ll]){ $whatTT=rand(2,4);
 ${"GLOBALS"}["auto_stop"][$ll]=0;
 $delayAsli=(int)$url_exp[1];
 if($delayAsli > 60){ $berapaLama=(int)($delayAsli*((int)$whatTT/2));
 }else{ $berapaLama=(int)($delayAsli*(int)$whatTT);
 } echo "\n==Terminal ".($ll+1)." Auto Stop:Menunggu ".$berapaLama." dtk\n";
 ${"GLOBALS"}["arr_time"][$ll] = date('Y-m-d H:i:s',strtotime('+'.$berapaLama.' seconds',strtotime($startTime)));
 }else{ ${"GLOBALS"}["auto_stop"][$ll]++;
 } } $ll++;
 } sleep(1);
 if($loopCek > 3600){ $loopCek=0;
 ${"GLOBALS"}["firstStart"]=date("Y-m-d H:i:s");
 echo "\n==Check running ".$loopCek." ## ".${"GLOBALS"}["firstStart"]." ##\n";
 $loopCek++;
 } } }else{ echo "kosong bro";
 } } function claim($url,$whatCur){ $curl=curl_init();
 curl_setopt($curl,CURLOPT_URL,$url);
 curl_setopt($curl,CURLOPT_RETURNTRANSFER,1);
 curl_setopt($curl,CURLOPT_REFERER,$url);
 curl_setopt($curl,CURLOPT_USERAGENT,"Mozilla/4.0 (compatible;
 MSIE 7.0;
	 Windows NT 6.1;
 Win64;
	 x64;
 Trident/4.0;
 Mozilla/4.0 (compatible;
 MSIE 6.0;
 Windows NT 5.1;
 SV1) ;
 NeoDownloader Embedded Web Browser from: http://bsalsa.com/;
 .NET CLR 2.0.50727;
 SLCC2;
 .NET CLR 3.5.30729;
 .NET CLR 3.0.30729)");
 curl_setopt($curl,CURLOPT_COOKIEJAR,"cookie");
 curl_setopt($curl,CURLOPT_COOKIEFILE,"cookie");
 $result=curl_exec($curl);
 curl_close($curl);
 $resExpl=explode("<div class=\"alert alert-success\">",$result);
 $resExpl2=explode("satoshi",$resExpl[1]);
 if(trim($resExpl2[0])==""){ $resExpl2=explode("doge",$resExpl[1]);
 } return trim($resExpl2[0]);
 } startClaim();
 } }else{ echo "\n=========================";
 echo "\n=========================";
 echo "\n=========================";
 echo "\n==🇨 🇾 🇧 🇪 🇷  🇯 🇲 🇧==";
 echo "\n=========================";
 echo "\nVersi saat ini: ".$versi."\n";
 echo "\nVersi terbaru: ".$cekVersi."\n";
 } 
?>